NAMESPACE Simatic.Ax.Library

    {axcode:docs-v0:@simatic-ax/lacyccom:MyClass.md}
    CLASS DummyClass

        VAR PUBLIC
        END_VAR

        VAR
        END_VAR

        /// Inline Comment for MyMethod. It will be shown, when you hover over the method
        /// This method has no parameters and no return value
        METHOD PUBLIC MyMethod
            ;
        END_METHOD

    END_CLASS

END_NAMESPACE